{% set version = "1.5-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tclust/tclust_{{ version }}.tar.gz
  sha256: 492674b30a465e5f4a22ba0ce5556ed4d8e57b29090f9b5b94ad655d064e6f8b

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('tclust')"           # [not win]
    - "\"%R%\" -e \"library('tclust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tclust
  license: GPL-3.0-only
  summary: Provides functions for robust trimmed clustering. The methods are described in Garcia-Escudero (2008) <doi:10.1214/07-AOS515>, Fritz et al. (2012) <doi:10.18637/jss.v047.i12> and others.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris

# Package: tclust
# Version: 1.4-1
# Date: 2018-05-24
# Title: Robust Trimmed Clustering
# Author: Agustin Mayo Iscar, Luis Angel Garcia Escudero, Heinrich Fritz
# Maintainer: Valentin Todorov <valentin.todorov@chello.at>
# Description: Provides functions for robust trimmed clustering. The methods are described in Garcia-Escudero (2008) <doi:10.1214/07-AOS515>, Fritz et al. (2012) <doi:10.18637/jss.v047.i12> and others.
# Depends: R (>= 2.12.0)
# Suggests: mclust, cluster, mvtnorm, sn
# License: GPL-3
# Repository: CRAN
# NeedsCompilation: yes
# Packaged: 2018-05-24 08:42:01 UTC; todorovv
# Date/Publication: 2018-05-24 21:50:22 UTC
