appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ojDxYmEbEH3F4TYsrhxWmg/4neEs7GYCZCZTLZYoY61MDhsW/CUE4dyaeNmFKoxq0n40HaOVgJr07vJMZIv2+udZ2HbP4KpPMVCUdxVy7vmBdgzhVKRF8TRMuJDAMH6Zega0Dxjqi5xZpfc0eEK/CZ3Ne+TNufkkN2b/McvQwzlINWA1wWhWdEiZKhKpd1Y+U6PHRMJX6r5rmIHG73nl94EKutOg37jOESjzmzPSg4kZC04O6R5YUGmXMXEDkFGcGsZR4o28WEzqi5dNIDiWLLUPZaMew953HD3ET72Tx1XvLTP1VILTHxv/QWn9c27g0CWagcMZdy7EBjjFbTnuoGVithUGqBKGw2x99uqRkmNO5xIaUMq+F363zEF9CqinRVNK1pieaD+Ga9yaCxSJFOGQIK4nnePYJOY9u0B9we6SbQllGLYkIPbXTe06D/23pvjOUzxeBg6cesSxKMlhiRDw6VgIYFyA+LgQ7KovF8c0cLwINwet0M+rogZYatTF4Lb6hDuPLT8mIUTHlET2bVImtny1w/683sSzmOQ5MriUaZZYIZJM0dzRyu2VeS1vCAUI1OPKZqERBo/+C0SZ4HAZx7/eQrSCD9wOGg6+WO5YEb+8MdYzj3iKZpuLxEHgWmHyALE8tdV3+xgflHDxAIKOpXoa8jdkTnzwmg/SZlw=
conda_forge_output_validation: false
